urls.jquery = `
https://code.jquery.com/jquery-1.0.1.js
https://code.jquery.com/jquery-1.0.1.pack.js
https://code.jquery.com/jquery-1.0.2.js
https://code.jquery.com/jquery-1.0.2.pack.js
https://code.jquery.com/jquery-1.0.3.js
https://code.jquery.com/jquery-1.0.3.pack.js
https://code.jquery.com/jquery-1.0.4.js
https://code.jquery.com/jquery-1.0.4.pack.js
https://code.jquery.com/jquery-1.0.js
https://code.jquery.com/jquery-1.0.pack.js
https://code.jquery.com/jquery-1.1.1.js
https://code.jquery.com/jquery-1.1.1.pack.js
https://code.jquery.com/jquery-1.1.2.js
https://code.jquery.com/jquery-1.1.2.pack.js
https://code.jquery.com/jquery-1.1.3.js
https://code.jquery.com/jquery-1.1.3.pack.js
https://code.jquery.com/jquery-1.1.4.js
https://code.jquery.com/jquery-1.1.4.pack.js
https://code.jquery.com/jquery-1.1.js
https://code.jquery.com/jquery-1.1.pack.js
https://code.jquery.com/jquery-1.10.0.js
https://code.jquery.com/jquery-1.10.0.min.js
https://code.jquery.com/jquery-1.10.1.js
https://code.jquery.com/jquery-1.10.1.min.js
https://code.jquery.com/jquery-1.10.2.js
https://code.jquery.com/jquery-1.10.2.min.js
https://code.jquery.com/jquery-1.11.0.js
https://code.jquery.com/jquery-1.11.0.min.js
https://code.jquery.com/jquery-1.11.1.js
https://code.jquery.com/jquery-1.11.1.min.js
https://code.jquery.com/jquery-1.11.2.js
https://code.jquery.com/jquery-1.11.2.min.js
https://code.jquery.com/jquery-1.11.3.js
https://code.jquery.com/jquery-1.11.3.min.js
https://code.jquery.com/jquery-1.12.0.js
https://code.jquery.com/jquery-1.12.0.min.js
https://code.jquery.com/jquery-1.12.1.js
https://code.jquery.com/jquery-1.12.1.min.js
https://code.jquery.com/jquery-1.12.2.js
https://code.jquery.com/jquery-1.12.2.min.js
https://code.jquery.com/jquery-1.12.3.js
https://code.jquery.com/jquery-1.12.3.min.js
https://code.jquery.com/jquery-1.12.4.js
https://code.jquery.com/jquery-1.12.4.min.js
https://code.jquery.com/jquery-1.2.1.js
https://code.jquery.com/jquery-1.2.1.min.js
https://code.jquery.com/jquery-1.2.1.pack.js
https://code.jquery.com/jquery-1.2.2.js
https://code.jquery.com/jquery-1.2.2.min.js
https://code.jquery.com/jquery-1.2.2.pack.js
https://code.jquery.com/jquery-1.2.3.js
https://code.jquery.com/jquery-1.2.3.min.js
https://code.jquery.com/jquery-1.2.3.pack.js
https://code.jquery.com/jquery-1.2.4.js
https://code.jquery.com/jquery-1.2.4.min.js
https://code.jquery.com/jquery-1.2.4.pack.js
https://code.jquery.com/jquery-1.2.5.js
https://code.jquery.com/jquery-1.2.5.min.js
https://code.jquery.com/jquery-1.2.5.pack.js
https://code.jquery.com/jquery-1.2.6.js
https://code.jquery.com/jquery-1.2.6.min.js
https://code.jquery.com/jquery-1.2.6.pack.js
https://code.jquery.com/jquery-1.2.js
https://code.jquery.com/jquery-1.2.min.js
https://code.jquery.com/jquery-1.2.pack.js
https://code.jquery.com/jquery-1.3.1.js
https://code.jquery.com/jquery-1.3.1.min.js
https://code.jquery.com/jquery-1.3.1.pack.js
https://code.jquery.com/jquery-1.3.2.js
https://code.jquery.com/jquery-1.3.2.min.js
https://code.jquery.com/jquery-1.3.2.pack.js
https://code.jquery.com/jquery-1.3.js
https://code.jquery.com/jquery-1.3.min.js
https://code.jquery.com/jquery-1.3.pack.js
https://code.jquery.com/jquery-1.4.1.js
https://code.jquery.com/jquery-1.4.1.min.js
https://code.jquery.com/jquery-1.4.2.js
https://code.jquery.com/jquery-1.4.2.min.js
https://code.jquery.com/jquery-1.4.3.js
https://code.jquery.com/jquery-1.4.3.min.js
https://code.jquery.com/jquery-1.4.4.js
https://code.jquery.com/jquery-1.4.4.min.js
https://code.jquery.com/jquery-1.4.js
https://code.jquery.com/jquery-1.4.min.js
https://code.jquery.com/jquery-1.5.1.js
https://code.jquery.com/jquery-1.5.1.min.js
https://code.jquery.com/jquery-1.5.2.js
https://code.jquery.com/jquery-1.5.2.min.js
https://code.jquery.com/jquery-1.5.js
https://code.jquery.com/jquery-1.5.min.js
https://code.jquery.com/jquery-1.6.1.js
https://code.jquery.com/jquery-1.6.1.min.js
https://code.jquery.com/jquery-1.6.2.js
https://code.jquery.com/jquery-1.6.2.min.js
https://code.jquery.com/jquery-1.6.3.js
https://code.jquery.com/jquery-1.6.3.min.js
https://code.jquery.com/jquery-1.6.4.js
https://code.jquery.com/jquery-1.6.4.min.js
https://code.jquery.com/jquery-1.6.js
https://code.jquery.com/jquery-1.6.min.js
https://code.jquery.com/jquery-1.7.0.js
https://code.jquery.com/jquery-1.7.0.min.js
https://code.jquery.com/jquery-1.7.1.js
https://code.jquery.com/jquery-1.7.1.min.js
https://code.jquery.com/jquery-1.7.2.js
https://code.jquery.com/jquery-1.7.2.min.js
https://code.jquery.com/jquery-1.7.js
https://code.jquery.com/jquery-1.7.min.js
https://code.jquery.com/jquery-1.8.0.js
https://code.jquery.com/jquery-1.8.0.min.js
https://code.jquery.com/jquery-1.8.1.js
https://code.jquery.com/jquery-1.8.1.min.js
https://code.jquery.com/jquery-1.8.2.js
https://code.jquery.com/jquery-1.8.2.min.js
https://code.jquery.com/jquery-1.8.3.js
https://code.jquery.com/jquery-1.8.3.min.js
https://code.jquery.com/jquery-1.9.0.js
https://code.jquery.com/jquery-1.9.0.min.js
https://code.jquery.com/jquery-1.9.1.js
https://code.jquery.com/jquery-1.9.1.min.js
https://code.jquery.com/jquery-1.x-git.js
https://code.jquery.com/jquery-1.x-git.min.js
https://code.jquery.com/jquery-2.0.0.js
https://code.jquery.com/jquery-2.0.0.min.js
https://code.jquery.com/jquery-2.0.1.js
https://code.jquery.com/jquery-2.0.1.min.js
https://code.jquery.com/jquery-2.0.2.js
https://code.jquery.com/jquery-2.0.2.min.js
https://code.jquery.com/jquery-2.0.3.js
https://code.jquery.com/jquery-2.0.3.min.js
https://code.jquery.com/jquery-2.1.0.js
https://code.jquery.com/jquery-2.1.0.min.js
https://code.jquery.com/jquery-2.1.1.js
https://code.jquery.com/jquery-2.1.1.min.js
https://code.jquery.com/jquery-2.1.2.js
https://code.jquery.com/jquery-2.1.2.min.js
https://code.jquery.com/jquery-2.1.3.js
https://code.jquery.com/jquery-2.1.3.min.js
https://code.jquery.com/jquery-2.1.4.js
https://code.jquery.com/jquery-2.1.4.min.js
https://code.jquery.com/jquery-2.2.0.js
https://code.jquery.com/jquery-2.2.0.min.js
https://code.jquery.com/jquery-2.2.1.js
https://code.jquery.com/jquery-2.2.1.min.js
https://code.jquery.com/jquery-2.2.2.js
https://code.jquery.com/jquery-2.2.2.min.js
https://code.jquery.com/jquery-2.2.3.js
https://code.jquery.com/jquery-2.2.3.min.js
https://code.jquery.com/jquery-2.2.4.js
https://code.jquery.com/jquery-2.2.4.min.js
https://code.jquery.com/jquery-2.x-git.js
https://code.jquery.com/jquery-2.x-git.min.js
https://code.jquery.com/jquery-3.0.0.js
https://code.jquery.com/jquery-3.0.0.min.js
https://code.jquery.com/jquery-3.0.0.slim.js
https://code.jquery.com/jquery-3.0.0.slim.min.js
https://code.jquery.com/jquery-3.1.0.js
https://code.jquery.com/jquery-3.1.0.min.js
https://code.jquery.com/jquery-3.1.0.slim.js
https://code.jquery.com/jquery-3.1.0.slim.min.js
https://code.jquery.com/jquery-3.1.1.js
https://code.jquery.com/jquery-3.1.1.min.js
https://code.jquery.com/jquery-3.1.1.slim.js
https://code.jquery.com/jquery-3.1.1.slim.min.js
https://code.jquery.com/jquery-3.2.0.js
https://code.jquery.com/jquery-3.2.0.min.js
https://code.jquery.com/jquery-3.2.0.slim.js
https://code.jquery.com/jquery-3.2.0.slim.min.js
https://code.jquery.com/jquery-3.2.1.js
https://code.jquery.com/jquery-3.2.1.min.js
https://code.jquery.com/jquery-3.2.1.slim.js
https://code.jquery.com/jquery-3.2.1.slim.min.js
https://code.jquery.com/jquery-3.3.0.js
https://code.jquery.com/jquery-3.3.0.min.js
https://code.jquery.com/jquery-3.3.0.slim.js
https://code.jquery.com/jquery-3.3.0.slim.min.js
https://code.jquery.com/jquery-3.3.1.js
https://code.jquery.com/jquery-3.3.1.min.js
https://code.jquery.com/jquery-3.3.1.slim.js
https://code.jquery.com/jquery-3.3.1.slim.min.js
https://code.jquery.com/jquery-3.4.0.js
https://code.jquery.com/jquery-3.4.0.min.js
https://code.jquery.com/jquery-3.4.0.slim.js
https://code.jquery.com/jquery-3.4.0.slim.min.js
https://code.jquery.com/jquery-3.4.1.js
https://code.jquery.com/jquery-3.4.1.min.js
https://code.jquery.com/jquery-3.4.1.slim.js
https://code.jquery.com/jquery-3.4.1.slim.min.js
https://code.jquery.com/jquery-3.5.0.js
https://code.jquery.com/jquery-3.5.0.min.js
https://code.jquery.com/jquery-3.5.0.slim.js
https://code.jquery.com/jquery-3.5.0.slim.min.js
https://code.jquery.com/jquery-3.5.1.js
https://code.jquery.com/jquery-3.5.1.min.js
https://code.jquery.com/jquery-3.5.1.slim.js
https://code.jquery.com/jquery-3.5.1.slim.min.js
https://code.jquery.com/jquery-3.x-git.js
https://code.jquery.com/jquery-3.x-git.min.js
https://code.jquery.com/jquery-3.x-git.slim.js
https://code.jquery.com/jquery-3.x-git.slim.min.js
https://code.jquery.com/jquery-git.js
https://code.jquery.com/jquery-git.min.js
https://code.jquery.com/jquery-git.slim.js
https://code.jquery.com/jquery-git.slim.min.js
https://code.jquery.com/jquery-migrate-1.0.0.js
https://code.jquery.com/jquery-migrate-1.0.0.min.js
https://code.jquery.com/jquery-migrate-1.1.0.js
https://code.jquery.com/jquery-migrate-1.1.0.min.js
https://code.jquery.com/jquery-migrate-1.1.1.js
https://code.jquery.com/jquery-migrate-1.1.1.min.js
https://code.jquery.com/jquery-migrate-1.2.0.js
https://code.jquery.com/jquery-migrate-1.2.0.min.js
https://code.jquery.com/jquery-migrate-1.2.1.js
https://code.jquery.com/jquery-migrate-1.2.1.min.js
https://code.jquery.com/jquery-migrate-1.3.0.js
https://code.jquery.com/jquery-migrate-1.3.0.min.js
https://code.jquery.com/jquery-migrate-1.4.0.js
https://code.jquery.com/jquery-migrate-1.4.0.min.js
https://code.jquery.com/jquery-migrate-1.4.1.js
https://code.jquery.com/jquery-migrate-1.4.1.min.js
https://code.jquery.com/jquery-migrate-3.0.0.js
https://code.jquery.com/jquery-migrate-3.0.0.min.js
https://code.jquery.com/jquery-migrate-3.0.1.js
https://code.jquery.com/jquery-migrate-3.0.1.min.js
https://code.jquery.com/jquery-migrate-3.1.0.js
https://code.jquery.com/jquery-migrate-3.1.0.min.js
https://code.jquery.com/jquery-migrate-3.2.0.js
https://code.jquery.com/jquery-migrate-3.2.0.min.js
https://code.jquery.com/jquery-migrate-3.3.0.js
https://code.jquery.com/jquery-migrate-3.3.0.min.js
https://code.jquery.com/jquery-migrate-git.js
https://code.jquery.com/jquery-migrate-git.min.js
https://code.jquery.com/ui/jquery-ui-git.js
https://code.jquery.com/ui/jquery-ui-git.css
https://code.jquery.com/ui/1.12.1/jquery-ui.js
https://code.jquery.com/ui/1.12.1/jquery-ui.min.js
https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.12.1/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.12.0/jquery-ui.js
https://code.jquery.com/ui/1.12.0/jquery-ui.min.js
https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.js
https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js
https://code.jquery.com/ui/1.12.0-rc.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.12.0-rc.1/jquery-ui.js
https://code.jquery.com/ui/1.12.0-rc.1/jquery-ui.min.js
https://code.jquery.com/ui/1.12.0-rc.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.12.0-beta.1/jquery-ui.js
https://code.jquery.com/ui/1.12.0-beta.1/jquery-ui.min.js
https://code.jquery.com/ui/1.12.0-beta.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.4/jquery-ui.js
https://code.jquery.com/ui/1.11.4/jquery-ui.min.js
https://code.jquery.com/ui/1.11.4/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.11.4/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.11.3/jquery-ui.js
https://code.jquery.com/ui/1.11.3/jquery-ui.min.js
https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.2/jquery-ui.js
https://code.jquery.com/ui/1.11.2/jquery-ui.min.js
https://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.1/jquery-ui.js
https://code.jquery.com/ui/1.11.1/jquery-ui.min.js
https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.0/jquery-ui.js
https://code.jquery.com/ui/1.11.0/jquery-ui.min.js
https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.0-beta.2/jquery-ui.js
https://code.jquery.com/ui/1.11.0-beta.2/jquery-ui.min.js
https://code.jquery.com/ui/1.11.0-beta.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.11.0-beta.1/jquery-ui.js
https://code.jquery.com/ui/1.11.0-beta.1/jquery-ui.min.js
https://code.jquery.com/ui/1.11.0-beta.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.10.4/jquery-ui.js
https://code.jquery.com/ui/1.10.4/jquery-ui.min.js
https://code.jquery.com/ui/1.10.4/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.10.4/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.10.3/jquery-ui.js
https://code.jquery.com/ui/1.10.3/jquery-ui.min.js
https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.10.2/jquery-ui.js
https://code.jquery.com/ui/1.10.2/jquery-ui.min.js
https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.10.1/jquery-ui.js
https://code.jquery.com/ui/1.10.1/jquery-ui.min.js
https://code.jquery.com/ui/1.10.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.10.0/jquery-ui.js
https://code.jquery.com/ui/1.10.0/jquery-ui.min.js
https://code.jquery.com/ui/1.10.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.10.0-rc.1/jquery-ui.js
https://code.jquery.com/ui/1.10.0-rc.1/jquery-ui.min.js
https://code.jquery.com/ui/1.10.0-rc.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.10.0-beta.1/jquery-ui.js
https://code.jquery.com/ui/1.10.0-beta.1/jquery-ui.min.js
https://code.jquery.com/ui/1.10.0-beta.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.9.2/jquery-ui.js
https://code.jquery.com/ui/1.9.2/jquery-ui.min.js
https://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.9.2/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.9.1/jquery-ui.js
https://code.jquery.com/ui/1.9.1/jquery-ui.min.js
https://code.jquery.com/ui/1.9.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.9.0/jquery-ui.js
https://code.jquery.com/ui/1.9.0/jquery-ui.min.js
https://code.jquery.com/ui/1.9.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.9.0-rc.1/jquery-ui.js
https://code.jquery.com/ui/1.9.0-rc.1/jquery-ui.min.js
https://code.jquery.com/ui/1.9.0-rc.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.9.0-beta.1/jquery-ui.js
https://code.jquery.com/ui/1.9.0-beta.1/jquery-ui.min.js
https://code.jquery.com/ui/1.9.0-beta.1/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.8.24/jquery-ui.js
https://code.jquery.com/ui/1.8.24/jquery-ui.min.js
https://code.jquery.com/ui/1.8.24/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.8.24/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.8.23/jquery-ui.js
https://code.jquery.com/ui/1.8.23/jquery-ui.min.js
https://code.jquery.com/ui/1.8.23/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.22/jquery-ui.js
https://code.jquery.com/ui/1.8.22/jquery-ui.min.js
https://code.jquery.com/ui/1.8.22/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.21/jquery-ui.js
https://code.jquery.com/ui/1.8.21/jquery-ui.min.js
https://code.jquery.com/ui/1.8.21/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.20/jquery-ui.js
https://code.jquery.com/ui/1.8.20/jquery-ui.min.js
https://code.jquery.com/ui/1.8.20/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.19/jquery-ui.js
https://code.jquery.com/ui/1.8.19/jquery-ui.min.js
https://code.jquery.com/ui/1.8.19/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.18/jquery-ui.js
https://code.jquery.com/ui/1.8.18/jquery-ui.min.js
https://code.jquery.com/ui/1.8.18/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.17/jquery-ui.js
https://code.jquery.com/ui/1.8.17/jquery-ui.min.js
https://code.jquery.com/ui/1.8.17/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.16/jquery-ui.js
https://code.jquery.com/ui/1.8.16/jquery-ui.min.js
https://code.jquery.com/ui/1.8.16/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.15/jquery-ui.js
https://code.jquery.com/ui/1.8.15/jquery-ui.min.js
https://code.jquery.com/ui/1.8.15/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.14/jquery-ui.js
https://code.jquery.com/ui/1.8.14/jquery-ui.min.js
https://code.jquery.com/ui/1.8.14/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.13/jquery-ui.js
https://code.jquery.com/ui/1.8.13/jquery-ui.min.js
https://code.jquery.com/ui/1.8.13/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.12/jquery-ui.js
https://code.jquery.com/ui/1.8.12/jquery-ui.min.js
https://code.jquery.com/ui/1.8.12/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.11/jquery-ui.js
https://code.jquery.com/ui/1.8.11/jquery-ui.min.js
https://code.jquery.com/ui/1.8.11/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.10/jquery-ui.js
https://code.jquery.com/ui/1.8.10/jquery-ui.min.js
https://code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.9/jquery-ui.js
https://code.jquery.com/ui/1.8.9/jquery-ui.min.js
https://code.jquery.com/ui/1.8.9/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.8/jquery-ui.js
https://code.jquery.com/ui/1.8.8/jquery-ui.min.js
https://code.jquery.com/ui/1.8.8/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.7/jquery-ui.js
https://code.jquery.com/ui/1.8.7/jquery-ui.min.js
https://code.jquery.com/ui/1.8.7/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.6/jquery-ui.js
https://code.jquery.com/ui/1.8.6/jquery-ui.min.js
https://code.jquery.com/ui/1.8.6/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.5/jquery-ui.js
https://code.jquery.com/ui/1.8.5/jquery-ui.min.js
https://code.jquery.com/ui/1.8.5/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.4/jquery-ui.js
https://code.jquery.com/ui/1.8.4/jquery-ui.min.js
https://code.jquery.com/ui/1.8.4/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.3/jquery-ui.js
https://code.jquery.com/ui/1.8.3/jquery-ui.min.js
https://code.jquery.com/ui/1.8.3/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.2/jquery-ui.js
https://code.jquery.com/ui/1.8.2/jquery-ui.min.js
https://code.jquery.com/ui/1.8.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.1/jquery-ui.js
https://code.jquery.com/ui/1.8.1/jquery-ui.min.js
https://code.jquery.com/ui/1.8.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.8.0/jquery-ui.js
https://code.jquery.com/ui/1.8.0/jquery-ui.min.js
https://code.jquery.com/ui/1.8.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.7.3/jquery-ui.js
https://code.jquery.com/ui/1.7.3/jquery-ui.min.js
https://code.jquery.com/ui/1.7.3/themes/base/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/black-tie/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/blitzer/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/cupertino/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/dark-hive/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/dot-luv/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/eggplant/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/excite-bike/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/flick/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/hot-sneaks/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/humanity/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/le-frog/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/mint-choc/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/overcast/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/pepper-grinder/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/redmond/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/south-street/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/start/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/sunny/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/swanky-purse/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/trontastic/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/ui-darkness/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/ui-lightness/jquery-ui.css
https://code.jquery.com/ui/1.7.3/themes/vader/jquery-ui.css
https://code.jquery.com/ui/1.7.2/jquery-ui.js
https://code.jquery.com/ui/1.7.2/jquery-ui.min.js
https://code.jquery.com/ui/1.7.2/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.7.1/jquery-ui.js
https://code.jquery.com/ui/1.7.1/jquery-ui.min.js
https://code.jquery.com/ui/1.7.1/themes/smoothness/jquery-ui.css
https://code.jquery.com/ui/1.7.0/jquery-ui.js
https://code.jquery.com/ui/1.7.0/jquery-ui.min.js
https://code.jquery.com/ui/1.7.0/themes/smoothness/jquery-ui.css
https://code.jquery.com/mobile/git/jquery.mobile-git.js
https://code.jquery.com/mobile/git/jquery.mobile-git.min.js
https://code.jquery.com/mobile/git/jquery.mobile-git.css
https://code.jquery.com/mobile/git/jquery.mobile-git.min.css
https://code.jquery.com/mobile/1.5.0-rc1/jquery.mobile-1.5.0-rc1.js
https://code.jquery.com/mobile/1.5.0-rc1/jquery.mobile-1.5.0-rc1.min.js
https://code.jquery.com/mobile/1.5.0-rc1/jquery.mobile-1.5.0-rc1.min.css
https://code.jquery.com/mobile/1.5.0-rc1/jquery.mobile.structure-1.5.0-rc1.min.css
https://code.jquery.com/mobile/1.5.0-alpha.1/jquery.mobile-1.5.0-alpha.1.js
https://code.jquery.com/mobile/1.5.0-alpha.1/jquery.mobile-1.5.0-alpha.1.min.js
https://code.jquery.com/mobile/1.5.0-alpha.1/jquery.mobile-1.5.0-alpha.1.min.css
https://code.jquery.com/mobile/1.5.0-alpha.1/jquery.mobile.structure-1.5.0-alpha.1.min.css
https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.js
https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js
https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css
https://code.jquery.com/mobile/1.4.5/jquery.mobile.structure-1.4.5.min.css
https://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.js
https://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.js
https://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.css
https://code.jquery.com/mobile/1.4.4/jquery.mobile.structure-1.4.4.min.css
https://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.js
https://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.js
https://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.css
https://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css
https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.js
https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js
https://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css
https://code.jquery.com/mobile/1.4.2/jquery.mobile.structure-1.4.2.min.css
https://code.jquery.com/mobile/1.4.1/jquery.mobile-1.4.1.js
https://code.jquery.com/mobile/1.4.1/jquery.mobile-1.4.1.min.js
https://code.jquery.com/mobile/1.4.1/jquery.mobile-1.4.1.min.css
https://code.jquery.com/mobile/1.4.1/jquery.mobile.structure-1.4.1.min.css
https://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.js
https://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js
https://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.css
https://code.jquery.com/mobile/1.4.0/jquery.mobile.structure-1.4.0.min.css
https://code.jquery.com/mobile/1.4.0-rc.1/jquery.mobile-1.4.0-rc.1.js
https://code.jquery.com/mobile/1.4.0-rc.1/jquery.mobile-1.4.0-rc.1.min.js
https://code.jquery.com/mobile/1.4.0-rc.1/jquery.mobile-1.4.0-rc.1.min.css
https://code.jquery.com/mobile/1.4.0-rc.1/jquery.mobile.structure-1.4.0-rc.1.min.css
https://code.jquery.com/mobile/1.4.0-beta.1/jquery.mobile-1.4.0-beta.1.js
https://code.jquery.com/mobile/1.4.0-beta.1/jquery.mobile-1.4.0-beta.1.min.js
https://code.jquery.com/mobile/1.4.0-beta.1/jquery.mobile-1.4.0-beta.1.min.css
https://code.jquery.com/mobile/1.4.0-beta.1/jquery.mobile.structure-1.4.0-beta.1.min.css
https://code.jquery.com/mobile/1.4.0-alpha.2/jquery.mobile-1.4.0-alpha.2.js
https://code.jquery.com/mobile/1.4.0-alpha.2/jquery.mobile-1.4.0-alpha.2.min.js
https://code.jquery.com/mobile/1.4.0-alpha.2/jquery.mobile-1.4.0-alpha.2.min.css
https://code.jquery.com/mobile/1.4.0-alpha.2/jquery.mobile.structure-1.4.0-alpha.2.min.css
https://code.jquery.com/mobile/1.4.0-alpha.1/jquery.mobile-1.4.0-alpha.1.js
https://code.jquery.com/mobile/1.4.0-alpha.1/jquery.mobile-1.4.0-alpha.1.min.js
https://code.jquery.com/mobile/1.4.0-alpha.1/jquery.mobile-1.4.0-alpha.1.min.css
https://code.jquery.com/mobile/1.4.0-alpha.1/jquery.mobile.structure-1.4.0-alpha.1.min.css
https://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.js
https://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js
https://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css
https://code.jquery.com/mobile/1.3.2/jquery.mobile.structure-1.3.2.min.css
https://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.js
https://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js
https://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css
https://code.jquery.com/mobile/1.3.1/jquery.mobile.structure-1.3.1.min.css
https://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.js
https://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js
https://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css
https://code.jquery.com/mobile/1.3.0/jquery.mobile.structure-1.3.0.min.css
https://code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile-1.3.0-rc.1.js
https://code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile-1.3.0-rc.1.min.js
https://code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile-1.3.0-rc.1.min.css
https://code.jquery.com/mobile/1.3.0-rc.1/jquery.mobile.structure-1.3.0-rc.1.min.css
https://code.jquery.com/mobile/1.3.0-beta.1/jquery.mobile-1.3.0-beta.1.js
https://code.jquery.com/mobile/1.3.0-beta.1/jquery.mobile-1.3.0-beta.1.min.js
https://code.jquery.com/mobile/1.3.0-beta.1/jquery.mobile-1.3.0-beta.1.min.css
https://code.jquery.com/mobile/1.3.0-beta.1/jquery.mobile.structure-1.3.0-beta.1.min.css
https://code.jquery.com/mobile/1.2.1/jquery.mobile-1.2.1.js
https://code.jquery.com/mobile/1.2.1/jquery.mobile-1.2.1.min.js
https://code.jquery.com/mobile/1.2.1/jquery.mobile-1.2.1.min.css
https://code.jquery.com/mobile/1.2.1/jquery.mobile.structure-1.2.1.min.css
https://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.js
https://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js
https://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css
https://code.jquery.com/mobile/1.2.0/jquery.mobile.structure-1.2.0.min.css
https://code.jquery.com/mobile/1.2.0-rc.2/jquery.mobile-1.2.0-rc.2.js
https://code.jquery.com/mobile/1.2.0-rc.2/jquery.mobile-1.2.0-rc.2.min.js
https://code.jquery.com/mobile/1.2.0-rc.2/jquery.mobile-1.2.0-rc.2.min.css
https://code.jquery.com/mobile/1.2.0-rc.2/jquery.mobile.structure-1.2.0-rc.2.min.css
https://code.jquery.com/mobile/1.2.0-rc.1/jquery.mobile-1.2.0-rc.1.js
https://code.jquery.com/mobile/1.2.0-rc.1/jquery.mobile-1.2.0-rc.1.min.js
https://code.jquery.com/mobile/1.2.0-rc.1/jquery.mobile-1.2.0-rc.1.min.css
https://code.jquery.com/mobile/1.2.0-rc.1/jquery.mobile.structure-1.2.0-rc.1.min.css
https://code.jquery.com/mobile/1.2.0-beta.1/jquery.mobile-1.2.0-beta.1.js
https://code.jquery.com/mobile/1.2.0-beta.1/jquery.mobile-1.2.0-beta.1.min.js
https://code.jquery.com/mobile/1.2.0-beta.1/jquery.mobile-1.2.0-beta.1.min.css
https://code.jquery.com/mobile/1.2.0-beta.1/jquery.mobile.structure-1.2.0-beta.1.min.css
https://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile-1.2.0-alpha.1.js
https://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile-1.2.0-alpha.1.min.js
https://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile-1.2.0-alpha.1.min.css
https://code.jquery.com/mobile/1.2.0-alpha.1/jquery.mobile.structure-1.2.0-alpha.1.min.css
https://code.jquery.com/mobile/1.1.2/jquery.mobile-1.1.2.js
https://code.jquery.com/mobile/1.1.2/jquery.mobile-1.1.2.min.js
https://code.jquery.com/mobile/1.1.2/jquery.mobile-1.1.2.min.css
https://code.jquery.com/mobile/1.1.2/jquery.mobile.structure-1.1.2.min.css
https://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.js
https://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js
https://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css
https://code.jquery.com/mobile/1.1.1/jquery.mobile.structure-1.1.1.min.css
https://code.jquery.com/mobile/1.1.1-rc.1/jquery.mobile-1.1.1-rc.1.js
https://code.jquery.com/mobile/1.1.1-rc.1/jquery.mobile-1.1.1-rc.1.min.js
https://code.jquery.com/mobile/1.1.1-rc.1/jquery.mobile-1.1.1-rc.1.min.css
https://code.jquery.com/mobile/1.1.1-rc.1/jquery.mobile.structure-1.1.1-rc.1.min.css
https://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.js
https://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js
https://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css
https://code.jquery.com/mobile/1.1.0/jquery.mobile.structure-1.1.0.min.css
https://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile-1.1.0-rc.2.js
https://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile-1.1.0-rc.2.min.js
https://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile-1.1.0-rc.2.min.css
https://code.jquery.com/mobile/1.1.0-rc.2/jquery.mobile.structure-1.1.0-rc.2.min.css
https://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.js
https://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.js
https://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.css
https://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile.structure-1.1.0-rc.1.min.css
https://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.js
https://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js
https://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css
https://code.jquery.com/mobile/1.0.1/jquery.mobile.structure-1.0.1.min.css
https://code.jquery.com/mobile/1.0/jquery.mobile-1.0.js
https://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js
https://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css
https://code.jquery.com/mobile/1.0/jquery.mobile.structure-1.0.min.css
https://code.jquery.com/mobile/1.0rc3/jquery.mobile-1.0rc3.js
https://code.jquery.com/mobile/1.0rc3/jquery.mobile-1.0rc3.min.js
https://code.jquery.com/mobile/1.0rc3/jquery.mobile-1.0rc3.min.css
https://code.jquery.com/mobile/1.0rc3/jquery.mobile.structure-1.0rc3.min.css
https://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.js
https://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.js
https://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.css
https://code.jquery.com/mobile/1.0rc2/jquery.mobile.structure-1.0rc2.min.css
https://code.jquery.com/mobile/1.0rc1/jquery.mobile-1.0rc1.js
https://code.jquery.com/mobile/1.0rc1/jquery.mobile-1.0rc1.min.js
https://code.jquery.com/mobile/1.0rc1/jquery.mobile-1.0rc1.min.css
https://code.jquery.com/mobile/1.0b3/jquery.mobile-1.0b3.js
https://code.jquery.com/mobile/1.0b3/jquery.mobile-1.0b3.min.js
https://code.jquery.com/mobile/1.0b3/jquery.mobile-1.0b3.min.css
https://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.js
https://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js
https://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.css
https://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.js
https://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.js
https://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.css
https://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.js
https://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.js
https://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css
https://code.jquery.com/mobile/1.0a4/jquery.mobile-1.0a4.js
https://code.jquery.com/mobile/1.0a4/jquery.mobile-1.0a4.min.js
https://code.jquery.com/mobile/1.0a4/jquery.mobile-1.0a4.min.css
https://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.js
https://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.js
https://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.css
https://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.js
https://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.js
https://code.jquery.com/mobile/1.0a2/jquery.mobile-1.0a2.min.css
https://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.js
https://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.js
https://code.jquery.com/mobile/1.0a1/jquery.mobile-1.0a1.min.css
https://code.jquery.com/color/jquery.color-git.js
https://code.jquery.com/color/jquery.color.svg-names-git.js
https://code.jquery.com/color/jquery.color.plus-names-git.js
https://code.jquery.com/color/jquery.color-2.2.0.js
https://code.jquery.com/color/jquery.color-2.2.0.min.js
https://code.jquery.com/color/jquery.color.svg-names-2.2.0.js
https://code.jquery.com/color/jquery.color.svg-names-2.2.0.min.js
https://code.jquery.com/color/jquery.color.plus-names-2.2.0.js
https://code.jquery.com/color/jquery.color.plus-names-2.2.0.min.js
https://code.jquery.com/color/jquery.color-2.1.2.js
https://code.jquery.com/color/jquery.color-2.1.2.min.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.2.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.2.min.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.2.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.2.min.js
https://code.jquery.com/color/jquery.color-2.1.1.js
https://code.jquery.com/color/jquery.color-2.1.1.min.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.1.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.1.min.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.1.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.1.min.js
https://code.jquery.com/color/jquery.color-2.1.0.js
https://code.jquery.com/color/jquery.color-2.1.0.min.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.0.js
https://code.jquery.com/color/jquery.color.svg-names-2.1.0.min.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.0.js
https://code.jquery.com/color/jquery.color.plus-names-2.1.0.min.js
https://code.jquery.com/color/jquery.color-2.0.0.js
https://code.jquery.com/color/jquery.color-2.0.0.min.js
https://code.jquery.com/color/jquery.color.svg-names-2.0.0.js
https://code.jquery.com/color/jquery.color.svg-names-2.0.0.min.js
https://code.jquery.com/color/jquery.color.plus-names-2.0.0.js
https://code.jquery.com/color/jquery.color.plus-names-2.0.0.min.js
https://code.jquery.com/qunit/qunit-git.js
https://code.jquery.com/qunit/qunit-git.css
https://code.jquery.com/qunit/qunit-2.10.0.js
https://code.jquery.com/qunit/qunit-2.10.0.css
https://code.jquery.com/qunit/qunit-2.9.3.js
https://code.jquery.com/qunit/qunit-2.9.3.css
https://code.jquery.com/qunit/qunit-2.9.2.js
https://code.jquery.com/qunit/qunit-2.9.2.css
https://code.jquery.com/qunit/qunit-2.9.1.js
https://code.jquery.com/qunit/qunit-2.9.1.css
https://code.jquery.com/qunit/qunit-2.9.0.js
https://code.jquery.com/qunit/qunit-2.9.0.css
https://code.jquery.com/qunit/qunit-2.8.0.js
https://code.jquery.com/qunit/qunit-2.8.0.css
https://code.jquery.com/qunit/qunit-2.7.1.js
https://code.jquery.com/qunit/qunit-2.7.1.css
https://code.jquery.com/qunit/qunit-2.7.0.js
https://code.jquery.com/qunit/qunit-2.7.0.css
https://code.jquery.com/qunit/qunit-2.6.2.js
https://code.jquery.com/qunit/qunit-2.6.2.css
https://code.jquery.com/qunit/qunit-2.6.1.js
https://code.jquery.com/qunit/qunit-2.6.1.css
https://code.jquery.com/qunit/qunit-2.6.0.js
https://code.jquery.com/qunit/qunit-2.6.0.css
https://code.jquery.com/qunit/qunit-2.5.1.js
https://code.jquery.com/qunit/qunit-2.5.1.css
https://code.jquery.com/qunit/qunit-2.5.0.js
https://code.jquery.com/qunit/qunit-2.5.0.css
https://code.jquery.com/qunit/qunit-2.4.1.js
https://code.jquery.com/qunit/qunit-2.4.1.css
https://code.jquery.com/qunit/qunit-2.4.0.js
https://code.jquery.com/qunit/qunit-2.4.0.css
https://code.jquery.com/qunit/qunit-2.3.3.js
https://code.jquery.com/qunit/qunit-2.3.3.css
https://code.jquery.com/qunit/qunit-2.3.2.js
https://code.jquery.com/qunit/qunit-2.3.2.css
https://code.jquery.com/qunit/qunit-2.3.1.js
https://code.jquery.com/qunit/qunit-2.3.1.css
https://code.jquery.com/qunit/qunit-2.3.0.js
https://code.jquery.com/qunit/qunit-2.3.0.css
https://code.jquery.com/qunit/qunit-2.2.1.js
https://code.jquery.com/qunit/qunit-2.2.1.css
https://code.jquery.com/qunit/qunit-2.2.0.js
https://code.jquery.com/qunit/qunit-2.2.0.css
https://code.jquery.com/qunit/qunit-2.1.1.js
https://code.jquery.com/qunit/qunit-2.1.1.css
https://code.jquery.com/qunit/qunit-2.1.0.js
https://code.jquery.com/qunit/qunit-2.1.0.css
https://code.jquery.com/qunit/qunit-2.0.1.js
https://code.jquery.com/qunit/qunit-2.0.1.css
https://code.jquery.com/qunit/qunit-2.0.0.js
https://code.jquery.com/qunit/qunit-2.0.0.css
https://code.jquery.com/qunit/qunit-1.23.1.js
https://code.jquery.com/qunit/qunit-1.23.1.css
https://code.jquery.com/qunit/qunit-1.23.0.js
https://code.jquery.com/qunit/qunit-1.23.0.css
https://code.jquery.com/qunit/qunit-1.22.0.js
https://code.jquery.com/qunit/qunit-1.22.0.css
https://code.jquery.com/qunit/qunit-1.21.0.js
https://code.jquery.com/qunit/qunit-1.21.0.css
https://code.jquery.com/qunit/qunit-1.20.0.js
https://code.jquery.com/qunit/qunit-1.20.0.css
https://code.jquery.com/qunit/qunit-1.19.0.js
https://code.jquery.com/qunit/qunit-1.19.0.css
https://code.jquery.com/qunit/qunit-1.18.0.js
https://code.jquery.com/qunit/qunit-1.18.0.css
https://code.jquery.com/qunit/qunit-1.17.1.js
https://code.jquery.com/qunit/qunit-1.17.1.css
https://code.jquery.com/qunit/qunit-1.17.0.js
https://code.jquery.com/qunit/qunit-1.17.0.css
https://code.jquery.com/qunit/qunit-1.16.0.js
https://code.jquery.com/qunit/qunit-1.16.0.css
https://code.jquery.com/qunit/qunit-1.15.0.js
https://code.jquery.com/qunit/qunit-1.15.0.css
https://code.jquery.com/qunit/qunit-1.14.0.js
https://code.jquery.com/qunit/qunit-1.14.0.css
https://code.jquery.com/qunit/qunit-1.13.0.js
https://code.jquery.com/qunit/qunit-1.13.0.css
https://code.jquery.com/qunit/qunit-1.12.0.js
https://code.jquery.com/qunit/qunit-1.12.0.css
https://code.jquery.com/qunit/qunit-1.11.0.js
https://code.jquery.com/qunit/qunit-1.11.0.css
https://code.jquery.com/qunit/qunit-1.10.0.js
https://code.jquery.com/qunit/qunit-1.10.0.css
https://code.jquery.com/qunit/qunit-1.9.0.js
https://code.jquery.com/qunit/qunit-1.9.0.css
https://code.jquery.com/qunit/qunit-1.5.0.js
https://code.jquery.com/qunit/qunit-1.5.0.css
https://code.jquery.com/qunit/qunit-1.2.0.js
https://code.jquery.com/qunit/qunit-1.2.0.css
https://code.jquery.com/qunit/qunit-1.1.0.js
https://code.jquery.com/qunit/qunit-1.1.0.css
https://code.jquery.com/qunit/qunit-1.0.0.js
https://code.jquery.com/qunit/qunit-1.0.0.css
https://code.jquery.com/pep/0.4.3/pep.js
https://code.jquery.com/pep/0.4.3/pep.min.js
https://code.jquery.com/pep/0.4.2/pep.js
https://code.jquery.com/pep/0.4.2/pep.min.js
https://code.jquery.com/pep/0.4.1/pep.js
https://code.jquery.com/pep/0.4.1/pep.min.js
https://code.jquery.com/pep/0.4.0/pep.js
https://code.jquery.com/pep/0.4.0/pep.min.js
https://code.jquery.com/pep/0.3.0/pep.js
https://code.jquery.com/pep/0.3.0/pep.min.js
`;
