var urls = urls || {};
urls.googleapis = `
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular-resource.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular-route.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-aria.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-touch.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular-resource.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular-animate.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular-messages.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular-sanitize.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-animate.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-cookies.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-messages.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-sanitize.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-touch.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-cookies.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-resource.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-sanitize.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular-animate.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular-resource.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular-animate.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular-aria.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular-messages.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular-touch.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular-animate.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular-resource.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular-route.min.js
http://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular.min.js
http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js
http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js
http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js
http://ajax.googleapis.com/ajax/libs/d3js/3.5.17/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/4.13.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.11.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.12.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.14.2/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.15.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.15.1/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.7.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.8.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.9.0/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.9.2/d3.min.js
http://ajax.googleapis.com/ajax/libs/d3js/5.9.7/d3.min.js
http://ajax.googleapis.com/ajax/libs/dojo/1.1.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.8/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.10.9/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.11.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.11.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.11.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.11.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.11.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.12.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.12.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.12.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.13.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.2.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.2.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.3.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.3.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.3.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.4.8/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.5.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.6.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.10/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.11/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.12/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.8/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.7.9/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.10/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.11/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.12/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.13/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.14/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.8/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.8.9/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.0/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.10/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.11/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.2/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.3/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.4/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.5/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.6/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.7/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.8/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/dojo/1.9.9/dojo/dojo.js
http://ajax.googleapis.com/ajax/libs/ext-core/3.0.0/ext-core.js
http://ajax.googleapis.com/ajax/libs/ext-core/3.1.0/ext-core.js
http://ajax.googleapis.com/ajax/libs/hammerjs/2.0.8/hammer.min.js
http://ajax.googleapis.com/ajax/libs/indefinite-observable/1.0.1/indefinite-observable.bundle.js
http://ajax.googleapis.com/ajax/libs/indefinite-observable/2.0.1/indefinite-observable.bundle.js
http://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js
http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js
http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.2.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7./jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.0.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.3/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.js
http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.4/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.5.0/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.0/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.0/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.1/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.1/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.2/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.2/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.3/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.3/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.4/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.4/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/minified/jquery-ui.min.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/flick/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/cupertino/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css?ver=4.9.13
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css?ver=4.9.14
http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.6.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.6.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.3/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.3/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/themes/ui-lightness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/cupertino/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.19/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.19/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.20/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.20/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/base/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/smoothness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js
http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css
http://ajax.googleapis.com/ajax/libs/material-motion/0.1.0/material-motion.bundle.js
http://ajax.googleapis.com/ajax/libs/mootools/1.1.1/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.1.2/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.1/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.2/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.3/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.5/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.2.6/mootools-yui-compressed.js
http://ajax.googleapis.com/ajax/libs/mootools/1.3.0/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.3.1/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.3.2/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.0/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.1/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.2/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.3/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.4/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.5.0/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.5.1/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.5.2/mootools.min.js
http://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.0.1/zawgyi_converter.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.0.1/zawgyi_detector.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.0/zawgyi_converter.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.0/zawgyi_detector.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.1/zawgyi_converter.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.1/zawgyi_detector.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.3/zawgyi_converter.min.js
http://ajax.googleapis.com/ajax/libs/myanmar-tools/1.1.3/zawgyi_detector.min.js
http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.3/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.6.1.0/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.1/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.2.0/prototype.js
http://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.1/scriptaculous.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.2/scriptaculous.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.8.3/scriptaculous.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/controls.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/effects.js
http://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js
http://ajax.googleapis.com/ajax/libs/shaka-player/1.6.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.0.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.0.8/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.0.9/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.0/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.1/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.2/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.3/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.4/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.7/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.8/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.1.9/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.0/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.1/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.10/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.4/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.7/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.8/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.2.9/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.0/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.1/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.10/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.2/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.3/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.4/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.7/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.8/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.3.9/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.0/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.1/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.2/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.3/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.4/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.4.7/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.0-beta/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.0-beta2/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.0-beta3/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.0/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.1/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.10/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.11/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.2/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.3/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.4/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.5/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.6/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.7/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.8/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/shaka-player/2.5.9/shaka-player.compiled.js
http://ajax.googleapis.com/ajax/libs/spf/2.0.0/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.0.1/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.1.0/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.1.1/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.1.2/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.2.0/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.3.0/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.3.1/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.3.2/spf.js
http://ajax.googleapis.com/ajax/libs/spf/2.4.0/spf.js
http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js
http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js
http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject_src.js
http://ajax.googleapis.com/ajax/libs/threejs/r84/three.min.js
http://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js?version=1
http://ajax.googleapis.com/ajax/libs/webfont/1.5.0/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.5.10/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.5.2/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.5.3/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.5.6/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js
http://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js?ver=5.5.2
http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js
http://ajax.googleapis.com/ajax/libs/yui/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css
http://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/connection/connection-min.js
http://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/connection/connection-min.js?v=423
http://ajax.googleapis.com/ajax/libs/yui/2.9.0/build/yuiloader-dom-event/yuiloader-dom-event.js
`;
