image: node:22

stages:
  - test
  - build

default:
  interruptible: true

.cache: &cache
  paths:
    - node_modules/

test:
  extends: .cache
  stage: test
  script:
    - npm ci --no-audit --no-fund
    - npm test
    - npm run typecheck
    - npm run lint:src
    - npm run lint:ext

build:
  extends: .cache
  stage: build
  needs: [test]
  script:
    - npm ci --no-audit --no-fund
    - npm run build
  artifacts:
    paths:
      - web-ext-artifacts/jslibcache.xpi
    expire_in: 1 week
